server:
  port: 8110

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/api?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: xyq20020620


Logging:
  level:
    com.wms: debug

